name: Lint Golang Codebase

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**/*.md'
  push:
    branches:
      - master
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - run: hack/setup-git-redirect.sh
      env:
        GITHUB_PAT: ${{ secrets.BOT_PAT }}
    - uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55.2
        args: --timeout 15m
